-- DO NOT EDIT THIS FILE
-- This file is automatically overwritten by the installer
-- Control script for AIO cooling system

local cf = require("config/cooling_functions")

function on_resume()
    cf.on_resume()
end

-- Silent AIO fan curve based on CPU temperature, adjust as needed based on your system and how silent you want it to be
-- Temps are based on Intel Core Ultra 7 270k plus with 360 AIO, adjust as needed for your CPU
local cpu_fan_curve =  { 
                        { sensor_value = 60, control_value = 20 }, -- Desktop idle / Light load
                        { sensor_value = 75, control_value = 40 }, -- Normal load / Gaming
                        { sensor_value = 80, control_value = 50 }, -- Stress test
                        { sensor_value = 90, control_value = 50 }, -- Stress test
                        { sensor_value = 100, control_value = 100 } } -- Critical temp, max RPM
                                                
-- Silent case fan curve based on CPU temperature, adjust as needed based on your system and how silent you want it to be
local case_fan_cpu_curve =  { 
                        { sensor_value = 60, control_value = 20 }, -- Desktop idle
                        { sensor_value = 75, control_value = 40 }, -- Normal load / Gaming
                        { sensor_value = 80, control_value = 50 }, -- Stress test
                        { sensor_value = 90, control_value = 50 }, -- Stress test
                        { sensor_value = 100, control_value = 100 } } -- Critical temp, max RPM

-- Silent VRM fan curve based on RAM temperature, adjust as needed based on your system and how silent you want it to be
local vrm_fan_cpu_curve =  { 
                        { sensor_value = 45, control_value = 20 },  -- Desktop idle
                        { sensor_value = 50, control_value = 50 }, --  High temp
                        { sensor_value = 80, control_value = 100 } } -- Critical high temp, max RPM

-- Silent case fan curve based on GPU temperature, adjust as needed based on your system and how silent you want it to be
-- Temps are based on NVIDIA RTX 5070 Ti
local case_fan_gpu_curve =  { 
                        { sensor_value = 45, control_value = 20 },  -- Desktop idle
                        { sensor_value = 55, control_value = 50 },  -- Gaming flat curve start
                        { sensor_value = 70, control_value = 50 },  -- Gaming flat curve end
                        { sensor_value = 80, control_value = 70 },  -- Stress test
                        { sensor_value = 100, control_value = 100 } } -- Critical temp, max RPM
                      
local cpu_temp_critical = false

function calculate_controls(sensors)
    local result = {}

    -- AIO fan: Based on CPU temperature
    local cpu_temp = sensors["CPU Package"] or 50

    -- Apply moving average
    cpu_temp = cf.apply_ema("CPU Package", cpu_temp)
   
    -- Apply fan curve
    local aio_fan_speed = cf.apply_linear_curve(cpu_temp, cpu_fan_curve)
   
    -- Apply hysteresis based on CPU temperature
    aio_fan_speed = cf.apply_hysteresis("AIO Fan", aio_fan_speed, cpu_temp, 30, 100, 4, 2)

    table.insert(result, { alias = "AIO Fan", value = aio_fan_speed })  

    -- AIO pump speed is fixed
    local aio_pump_speed = 80
    
    if cpu_temp < 95 then
        cpu_temp_critical = false
    end
    if cpu_temp >= 100 or cpu_temp_critical then
        cpu_temp_critical = true
        aio_pump_speed = 100
    end
    
    table.insert(result, { alias = "AIO Pump", value = aio_pump_speed })
  
    -- Case fan: Based on CPU temperature
    
    -- Apply fan curve
    local case_fan_cpu_speed = cf.apply_linear_curve(cpu_temp, case_fan_cpu_curve)

    -- Apply hysteresis based on CPU temperature
    case_fan_cpu_speed = cf.apply_hysteresis("Case Fan CPU", case_fan_cpu_speed, cpu_temp, 30, 100, 4, 2)
 
    -- Case fan: Based on GPU temperature
    local gpu_temp = sensors["GPU Core"] or 50

    -- Apply moving average
    gpu_temp = cf.apply_ema("GPU Core", gpu_temp)

    -- Apply fan curve
    local case_fan_gpu_speed = cf.apply_linear_curve(gpu_temp, case_fan_gpu_curve)

    -- Apply hysteresis based on GPU temperature
    case_fan_gpu_speed = cf.apply_hysteresis("Case Fan GPU", case_fan_gpu_speed, gpu_temp, 45, 100, 4, 2)

    -- Mix the two curves, use gpu fan curve only if GPU fans are spinning, otherwise use only CPU fan curve.
    local gpu_fan_1_rpm = sensors["GPU Fan 1"] or 0
    local gpu_fan_2_rpm = sensors["GPU Fan 2"] or 0
    local case_fan_speed
    if gpu_fan_1_rpm > 0 or gpu_fan_2_rpm > 0 then
        case_fan_speed =  math.max(case_fan_cpu_speed, case_fan_gpu_speed)
    else
        case_fan_speed = case_fan_cpu_speed
    end
    
    table.insert(result, { alias = "Front Fan", value = case_fan_speed })
    table.insert(result, { alias = "Rear Fan", value = case_fan_speed })
  
    -- VRM fan: Based on RAM temperature
    local dimm1_temp = sensors["DIMM 1"] or 40
    local dimm3_temp = sensors["DIMM 3"] or 40

    -- Apply moving average
    dimm1_temp = cf.apply_ema("DIMM 1", dimm1_temp)
    dimm3_temp = cf.apply_ema("DIMM 3", dimm3_temp)
    local dimm_temp = math.max(dimm1_temp, dimm3_temp)

    -- Apply fan curve
    local vrm_fan_speed = cf.apply_linear_curve(dimm_temp, vrm_fan_cpu_curve)

    -- Apply hysteresis based on RAM temperature
    vrm_fan_speed = cf.apply_hysteresis("VRM Fan", vrm_fan_speed, dimm_temp, 30, 100, 4, 2)

    table.insert(result, { alias = "VRM Fan", value = vrm_fan_speed })

    return result
end