-- DO NOT EDIT THIS FILE
-- This file is automatically overwritten by the installer
-- Control script for GPU cooling

local cf = require("config/cooling_functions")

function on_resume()
    cf.on_resume()
end


--- GPU fan curve based on GPU temperature, adjust as needed
-- This curve is for an MSI RTX 4070 Super Ventus 2X OC, it allow to turn off the fan until 62C.
local gpu_fan_curve = { { sensor_value = 61, control_value = 0 }, { sensor_value = 62, control_value = 30 }, { sensor_value = 83, control_value = 60 } }

function calculate_controls(sensors)
    local result = {}

    -- GPU fan control based on GPU temperature
    local gpu_temp = sensors["GPU Core"] or 50

    -- Apply moving average
    gpu_temp = cf.apply_ema("GPU Core", gpu_temp)

    -- Apply fan curve
    local gpu_fan_speed = cf.apply_linear_curve(gpu_temp, gpu_fan_curve)

    -- Apply hysteresis based on GPU temperature
    gpu_fan_speed = cf.apply_hysteresis("GPU Fan", gpu_fan_speed, gpu_temp, 50, 83, 1, 2)

    table.insert(result, { alias = "GPU Fan", value = gpu_fan_speed })

    return result
end