-- DO NOT EDIT THIS FILE
-- This file is automatically overwritten by the installer
-- Control script for AIO cooling system with coolant sensor

local cf = require("config/cooling_functions")

function on_resume()
    cf.on_resume()
end

-- AIO coolant target temperature, adjust as needed
local aio_coolant_target_temp = 40

-- AIO fan RPM limits (not absolute limits), adjust as needed based on your AIO and how silent you want it to be
-- Increasing fan speed reduces CPU temperature, but the effect diminishes at higher speeds
-- High fan speeds may increase noise without proportional cooling benefits
local min_aio_fan_rpm = 600
local max_aio_fan_rpm = 1800

-- Silent case fan curve based on CPU temperature, adjust as needed based on your system and how silent you want it to be
local case_fan_cpu_curve =  { 
                        { sensor_value = 60, control_value = 20 },  -- Desktop idle
                        { sensor_value = 75, control_value = 50 }, -- Normal load / Gaming
                        { sensor_value = 95, control_value = 100 } } -- Critical temp, max RPM

-- Silent case fan curve based on GPU temperature, adjust as needed based on your system and how silent you want it to be
-- Temps are based on NVIDIA RTX 5070 Ti
local case_fan_gpu_curve =  { 
                        { sensor_value = 45, control_value = 20 },  -- Desktop idle
                        { sensor_value = 55, control_value = 50 },  -- Gaming flat curve start
                        { sensor_value = 68, control_value = 50 },  -- Gaming flat curve end
                        { sensor_value = 76, control_value = 70 } } -- Stress test

function calculate_controls(sensors)
    local result = {}

    local coolant_temp = sensors["T Sensor"] or 40

    -- Calc AIO fan
    local aio_fan_rpm = cf.aio_fan_pid_control("T Sensor", coolant_temp, aio_coolant_target_temp, min_aio_fan_rpm, max_aio_fan_rpm)  
    
    table.insert(result, { alias = "AIO Fan", rpm = aio_fan_rpm })

    -- AIO pump speed is fixed
    local aio_pump_speed = 80

    table.insert(result, { alias = "AIO Pump", value = aio_pump_speed })

    -- Case fan: Based on CPU temperature
    local cpu_temp = sensors["CPU Package"] or 50

    -- Apply moving average
    cpu_temp = cf.apply_ema("CPU Package", cpu_temp)

    -- Apply fan curve
    local case_fan_cpu_speed = cf.apply_linear_curve(cpu_temp, case_fan_cpu_curve)

    -- Apply hysteresis based on CPU temperature
    case_fan_cpu_speed = cf.apply_hysteresis("Case Fan CPU", case_fan_cpu_speed, cpu_temp, 30, 100, 4, 2)
 
    -- Case fan: Based on GPU board power
    local gpu_temp = sensors["GPU Core"] or 50

    -- Apply moving average
    gpu_temp = cf.apply_ema("GPU Core", gpu_temp)

    -- Apply fan curve
    local case_fan_gpu_speed = cf.apply_linear_curve(gpu_temp, case_fan_gpu_curve)

    -- Apply hysteresis based on GPU temperature
    case_fan_gpu_speed = cf.apply_hysteresis("Case Fan GPU", case_fan_gpu_speed, gpu_temp, 45, 83, 4, 2)

    -- Mix the two curves, use gpu fan curve only if GPU fans are spinning, otherwise use only CPU fan curve.
    local gpu_fan_1_rpm = sensors["GPU Fan 1"] or 0
    local gpu_fan_2_rpm = sensors["GPU Fan 2"] or 0
    local case_fan_speed
    if gpu_fan_1_rpm > 0 or gpu_fan_2_rpm > 0 then
        case_fan_speed =  math.max(case_fan_cpu_speed, case_fan_gpu_speed)
    else
        case_fan_speed = case_fan_cpu_speed
    end
    
    table.insert(result, { alias = "Case Fan", value = case_fan_speed })
  
    return result
end