-- DO NOT EDIT THIS FILE
-- This file is automatically overwritten by the installer
-- Control script for AIO cooling system

local cf = require("config/cooling_functions")

function on_start()
  log_information("CoolingControl started")
  -- Example: Log control and sensor configuration
  for alias, ctrl in pairs(control_config) do
      log_information("Control: " .. alias .. " (identifier=" .. ctrl.identifier .. ", rpm_sensor=" .. ctrl.rpm_sensor .. ")")
  end
  for alias, sensor in pairs(sensor_config) do
      log_information("Sensor: " .. alias .. " (identifier=" .. sensor.identifier .. ")")
  end
end


function on_resume()
    cf.on_resume()
end

function calculate_controls(sensors)
    local result = {}

    -- Use one of samples or write your own algorithm

    return result
end
