-- DO NOT EDIT THIS FILE
-- This file is automatically overwritten by the installer
-- AIO sample with silent, balanced, and performance curves.
-- Temperatures are starting points (Core Ultra 7 270K, 360 AIO, RTX 5070 Ti). Edit them for your hardware.
-- Select this file with ScriptPath and list the same names in Profiles.

local cf = require("config/cooling_functions")

local curves = {
    silent = {
        cpu_fan = {
            { sensor_value = 60, control_value = 20 },
            { sensor_value = 75, control_value = 40 },
            { sensor_value = 80, control_value = 50 },
            { sensor_value = 90, control_value = 50 },
            { sensor_value = 100, control_value = 100 }
        },
        case_fan_cpu = {
            { sensor_value = 60, control_value = 20 },
            { sensor_value = 75, control_value = 40 },
            { sensor_value = 80, control_value = 50 },
            { sensor_value = 90, control_value = 50 },
            { sensor_value = 100, control_value = 100 }
        },
        vrm_fan = {
            { sensor_value = 45, control_value = 20 },
            { sensor_value = 50, control_value = 50 },
            { sensor_value = 80, control_value = 100 }
        },
        case_fan_gpu = {
            { sensor_value = 45, control_value = 20 },
            { sensor_value = 55, control_value = 50 },
            { sensor_value = 70, control_value = 50 },
            { sensor_value = 80, control_value = 70 },
            { sensor_value = 100, control_value = 100 }
        }
    },
    balanced = {
        cpu_fan = {
            { sensor_value = 55, control_value = 30 },
            { sensor_value = 70, control_value = 55 },
            { sensor_value = 75, control_value = 70 },
            { sensor_value = 85, control_value = 80 },
            { sensor_value = 100, control_value = 100 }
        },
        case_fan_cpu = {
            { sensor_value = 55, control_value = 30 },
            { sensor_value = 70, control_value = 55 },
            { sensor_value = 75, control_value = 70 },
            { sensor_value = 85, control_value = 80 },
            { sensor_value = 100, control_value = 100 }
        },
        vrm_fan = {
            { sensor_value = 40, control_value = 30 },
            { sensor_value = 48, control_value = 60 },
            { sensor_value = 75, control_value = 100 }
        },
        case_fan_gpu = {
            { sensor_value = 40, control_value = 30 },
            { sensor_value = 50, control_value = 60 },
            { sensor_value = 65, control_value = 60 },
            { sensor_value = 75, control_value = 80 },
            { sensor_value = 100, control_value = 100 }
        }
    },
    performance = {
        cpu_fan = {
            { sensor_value = 45, control_value = 40 },
            { sensor_value = 60, control_value = 70 },
            { sensor_value = 70, control_value = 85 },
            { sensor_value = 80, control_value = 95 },
            { sensor_value = 100, control_value = 100 }
        },
        case_fan_cpu = {
            { sensor_value = 45, control_value = 40 },
            { sensor_value = 60, control_value = 70 },
            { sensor_value = 70, control_value = 85 },
            { sensor_value = 80, control_value = 95 },
            { sensor_value = 100, control_value = 100 }
        },
        vrm_fan = {
            { sensor_value = 35, control_value = 40 },
            { sensor_value = 45, control_value = 75 },
            { sensor_value = 70, control_value = 100 }
        },
        case_fan_gpu = {
            { sensor_value = 35, control_value = 40 },
            { sensor_value = 45, control_value = 70 },
            { sensor_value = 60, control_value = 70 },
            { sensor_value = 70, control_value = 90 },
            { sensor_value = 100, control_value = 100 }
        }
    }
}

local cpu_temp_critical = false

function on_resume()
    cf.on_resume()
end

function on_profile_changed(name)
    cf.on_resume()
end

local function curve_for_profile()
    local selected = curves[active_profile]
    if selected == nil then
        selected = curves.balanced
    end
    return selected
end

function calculate_controls(sensors)
    local result = {}
    local curve = curve_for_profile()

    local cpu_temp = sensors["CPU Package"] or 50
    cpu_temp = cf.apply_ema("CPU Package", cpu_temp)

    local aio_fan_speed = cf.apply_linear_curve(cpu_temp, curve.cpu_fan)
    aio_fan_speed = cf.apply_hysteresis("AIO Fan", aio_fan_speed, cpu_temp, 30, 100, 4, 2)
    table.insert(result, { alias = "AIO Fan", value = aio_fan_speed })

    local aio_pump_speed = 80
    if cpu_temp < 95 then
        cpu_temp_critical = false
    end
    if cpu_temp >= 100 or cpu_temp_critical then
        cpu_temp_critical = true
        aio_pump_speed = 100
    end
    table.insert(result, { alias = "AIO Pump", value = aio_pump_speed })

    local case_fan_cpu_speed = cf.apply_linear_curve(cpu_temp, curve.case_fan_cpu)
    case_fan_cpu_speed = cf.apply_hysteresis("Case Fan CPU", case_fan_cpu_speed, cpu_temp, 30, 100, 4, 2)

    local gpu_temp = sensors["GPU Core"] or 50
    gpu_temp = cf.apply_ema("GPU Core", gpu_temp)
    local case_fan_gpu_speed = cf.apply_linear_curve(gpu_temp, curve.case_fan_gpu)
    case_fan_gpu_speed = cf.apply_hysteresis("Case Fan GPU", case_fan_gpu_speed, gpu_temp, 45, 100, 4, 2)

    local gpu_fan_1_rpm = sensors["GPU Fan 1"] or 0
    local gpu_fan_2_rpm = sensors["GPU Fan 2"] or 0
    local case_fan_speed
    if gpu_fan_1_rpm > 0 or gpu_fan_2_rpm > 0 then
        case_fan_speed = math.max(case_fan_cpu_speed, case_fan_gpu_speed)
    else
        case_fan_speed = case_fan_cpu_speed
    end
    table.insert(result, { alias = "Front Fan", value = case_fan_speed })
    table.insert(result, { alias = "Rear Fan", value = case_fan_speed })

    local dimm1_temp = sensors["DIMM 1"] or 40
    local dimm3_temp = sensors["DIMM 3"] or 40
    dimm1_temp = cf.apply_ema("DIMM 1", dimm1_temp)
    dimm3_temp = cf.apply_ema("DIMM 3", dimm3_temp)
    local dimm_temp = math.max(dimm1_temp, dimm3_temp)
    local vrm_fan_speed = cf.apply_linear_curve(dimm_temp, curve.vrm_fan)
    vrm_fan_speed = cf.apply_hysteresis("VRM Fan", vrm_fan_speed, dimm_temp, 30, 100, 4, 2)
    table.insert(result, { alias = "VRM Fan", value = vrm_fan_speed })

    return result
end
