-- DO NOT EDIT THIS FILE
-- This file is automatically overwritten by the installer
-- Control script for AIO cooling system

local cf = require("config/cooling_functions")

function on_resume()
    cf.on_resume()
end

-- Silent AIO fan curve base on CPU temperature, adjust as needed based on your system and how silent you want it to be
local cpu_fan_curve =  { 
                        { sensor_value = 45, control_value = 600 }, 
                        { sensor_value = 65, control_value = 900 },
                        { sensor_value = 78, control_value = 1300 }, 
                        { sensor_value = 85, control_value = 2230 } } 

-- Silent case fan curve base on GPU temperature, adjust as needed based on your system and how silent you want it to be
local case_fan_curve =  { 
                        { sensor_value = 62, control_value = 500 }, 
                        { sensor_value = 68, control_value = 700 },
                        { sensor_value = 75, control_value = 1000 }, 
                        { sensor_value = 83, control_value = 1600 } } 
                        

-- max_case_fan_speed / max_aio_fan_speed
local case_aio_fan_scale = 1600 / 2230

function calculate_controls(sensors)
    local result = {}

    local cpu_temp = sensors["CPU Package"] or 50

    -- Apply moving average
    cpu_temp = cf.apply_ema("CPU Package", cpu_temp)
   
    -- Calc AIO fan
    local aio_fan_rpm = cf.apply_linear_curve(cpu_temp, cpu_fan_curve)
   
    -- Apply hysteresis based on CPU temperature
    aio_fan_rpm = cf.apply_hysteresis("AIO Fan", aio_fan_rpm, cpu_temp, 30, 100, 4, 2)

    table.insert(result, { alias = "AIO Fan", rpm = aio_fan_rpm })  

    -- AIO pump speed is fixed
    local aio_pump_speed = 80
    table.insert(result, { alias = "AIO Pump", value = aio_pump_speed })
  
    -- Case fan: Based on GPU board power mixed with AIO fan
    local gpu_temp = sensors["GPU Core"] or 50

    -- Apply moving average
    gpu_temp = cf.apply_ema("GPU Core", gpu_temp)

    -- Apply fan curve
    local case_fan_rpm = cf.apply_linear_curve(gpu_temp, case_fan_curve)

    -- Apply hysteresis based on GPU temperature
    case_fan_rpm = cf.apply_hysteresis("Case Fan", case_fan_rpm, gpu_temp, 45, 83, 4, 2)

    -- Mix with AIO fan, max 1600 RPM for case fan to keep it quiet
    case_fan_rpm = math.min(1600, math.max(aio_fan_rpm * case_aio_fan_scale, case_fan_rpm))
    
    table.insert(result, { alias = "Case Fan", rpm = case_fan_rpm })
  
    return result
end