-- DO NOT EDIT THIS FILE
-- This file is automatically overwritten by the installer
-- Control script for AIO cooling system with coolant sensor

local cf = require("config/cooling_functions")

function on_resume()
    cf.on_resume()
end

-- AIO coolant target temperature, adjust as needed
local aio_coolant_target_temp = 40

-- AIO fan RPM limits (not absolute limits), adjust as needed based on your AIO and how silent you want it to be
-- Increasing fan speed reduces CPU temperature, but the effect diminishes at higher speeds
-- High fan speeds may increase noise without proportional cooling benefits
local min_aio_fan_rpm = 600
local max_aio_fan_rpm = 1800


-- Silent case fan curve base on GPU temperature, adjust as needed based on your system and how silent you want it to be
local case_fan_curve =  { 
                        { sensor_value = 62, control_value = 500 }, 
                        { sensor_value = 68, control_value = 700 },
                        { sensor_value = 75, control_value = 1000 }, 
                        { sensor_value = 83, control_value = 1600 } } 


local case_aio_fan_scale = 1600 / max_aio_fan_rpm

function calculate_controls(sensors)
    local result = {}

    local coolant_temp = sensors["T Sensor"] or 40

    -- Calc AIO fan
    local aio_fan_rpm = cf.aio_fan_pid_control("T Sensor", coolant_temp, aio_coolant_target_temp, min_aio_fan_rpm, max_aio_fan_rpm)  
    
    table.insert(result, { alias = "AIO Fan", rpm = aio_fan_rpm })

    -- AIO pump speed is fixed
    local aio_pump_speed = 80

    table.insert(result, { alias = "AIO Pump", value = aio_pump_speed })

    -- Case fan: Based on GPU temperature mixed with AIO fan
    local gpu_temp = sensors["GPU Core"] or 50

    -- Apply moving average
    gpu_temp = cf.apply_ema("GPU Core", gpu_temp)

    -- Apply fan curve
    local case_fan_rpm = cf.apply_linear_curve(gpu_temp, case_fan_curve)

    -- Apply hysteresis based on GPU temperature
    case_fan_rpm = cf.apply_hysteresis("Case Fan", case_fan_rpm, gpu_temp, 45, 83, 4, 2)

    -- Mix with AIO fan, max 1600 RPM for case fan to keep it quiet
    case_fan_rpm = math.min(1600, math.max(aio_fan_rpm * case_aio_fan_scale, case_fan_rpm))
    
    table.insert(result, { alias = "Case Fan", rpm = case_fan_rpm })
  
    return result
end